routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('frontend.index');
Route::get('jadwal-pmb', 'WelcomeController@jadwal')->name('frontend.jadwal');
Route::get('informasi-pendaftaran', 'WelcomeController@informasi')->name('frontend.informasi');
Route::get('brosur-pmb', 'WelcomeController@brosur')->name('frontend.brosur');
Route::get('dokumen-pmb', 'WelcomeController@dokumen')->name('frontend.dokumen');
Route::resource('post', 'PostController');

Route::get('/register-success', 'WelcomeController@register_success');
Route::get('/aktifasi', 'WelcomeController@aktifasi')->name('aktifasi');
Route::get('/aktifasi-resend', 'WelcomeController@aktifasi_resend')->name('aktifasi.resend');
Route::post('/aktifasi-send', 'WelcomeController@aktifasi_send')->name('aktifasi.send');
Route::get('/viewfile', 'ViewFileController@index')->name('viewfile');

Auth::routes();

Route::group(['middleware' => 'auth'], function ()
{
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/profile', 'HomeController@profile')->name('profile');
	Route::put('/profile/{id}/update', 'HomeController@update')->name('profile.update');

    Route::group(['middleware' => 'roles', 'roles' => 'administrator'], function ()
    {
		Route::get('admin', 'Admin\AdminController@index');
		Route::resource('admin/roles', 'Admin\RolesController');
		Route::resource('admin/permissions', 'Admin\PermissionsController');
		Route::resource('admin/users', 'Admin\UsersController');
		Route::resource('admin/pages', 'Admin\PagesController');
		Route::resource('admin/activitylogs', 'Admin\ActivityLogsController')->only([
		    'index', 'show', 'destroy'
		]);
		Route::resource('admin/settings', 'Admin\SettingsController');
		Route::get('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@getGenerator']);
		Route::post('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@postGenerator']);
		
		Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
	});

    Route::group(['middleware' => 'roles', 'roles' => ['siswa', 'admin_pusat']], function ()
    {
        Route::resource('siswa', 'SiswaController');
        Route::resource('pegawai', 'PegawaiController');
    });

    Route::group(['middleware' => 'roles', 'roles' => ['siswa', 'admin_pusat', 'operator']], function ()
    {
        Route::resource('pendaftaran', 'PendaftaranController');
    });

    Route::group(['middleware' => 'roles', 'roles' => ['admin_pusat', 'operator']], function ()
    {
        Route::get('list-pendaftaran', 'PendaftaranController@list')->name('pendaftaran.list');
    });

    Route::group(['middleware' => 'roles', 'roles' => 'siswa'], function ()
    {
		Route::get('pemilihan-jalur', 'PendaftaranController@jalur')->name('pilih-jalur');
		Route::post('jalur/simpan-jalur', 'PendaftaranController@store_jalur')->name('store-jalur');
		Route::get('jurusan/pemilihan-jurusan', 'PendaftaranController@jurusan')->name('pilih-jurusan');
		Route::post('jurusan/simpan-jurusan', 'PendaftaranController@store_jurusan')->name('store-jurusan');
		Route::resource('prestasi', 'PrestasiController');
		Route::get('resume', 'PendaftaranController@resume')->name('pendaftaran.resume');
        Route::get('siswa/kartu/cetak', 'SiswaController@kartu')->name('siswa.kartu');
	});

    Route::group(['middleware' => 'roles', 'roles' => 'admin_pusat'], function ()
    {
        Route::resource('tes-wawancara', 'WawancaraController');
        Route::get('tes-wawancara/download/pdf', 'WawancaraController@pdf')->name('tes-wawancara.pdf');
        Route::get('tes-wawancara/download/xls', 'WawancaraController@xls')->name('tes-wawancara.xls');
        Route::resource('tes-kesehatan', 'TesKesehatanController');
        Route::get('tes-kesehatan/download/pdf', 'TesKesehatanController@pdf')->name('tes-kesehatan.pdf');
        Route::get('tes-kesehatan/download/xls', 'TesKesehatanController@xls')->name('tes-kesehatan.xls');
        Route::resource('verifikasi-akhir', 'VerifikasiAkhirController');
        Route::post('verifikasi-akhir/generate', 'VerifikasiAkhirController@generate')->name('generate-jurusan');

        Route::resource('cms', 'ContentController');
		Route::resource('jadwal', 'JadwalController');
    });

    Route::group(['middleware' => 'roles', 'roles' => 'operator'], function ()
    {
        Route::resource('verifikasi-dokumen', 'VerifikasiDokumenController');
        Route::resource('tes-tulis', 'TesTulisController');
        Route::get('tes-tulis/download/pdf', 'TesTulisController@pdf')->name('tes-tulis.pdf');
        Route::get('tes-tulis/download/xls', 'TesTulisController@xls')->name('tes-tulis.xls');
    });

    Route::group(['namespace' => 'Api', 'prefix' => 'api'], function () {
        Route::group(['prefix' => '/siswa'], function () {
            Route::get('/', 'SiswaController@index')->name('api.siswa');
        });
        Route::group(['prefix' => '/verifikasi-dokumen'], function () {
            Route::get('/', 'VerifikasiDokumenController@index')->name('api.verifikasi');
        });
        Route::group(['prefix' => '/tes-tulis'], function () {
            Route::get('/', 'TesTulisController@index')->name('api.tulis');
        });
        Route::group(['prefix' => '/tes-wawancara'], function () {
            Route::get('/', 'WawancaraController@index')->name('api.wawancara');
        });
        Route::group(['prefix' => '/tes-kesehatan'], function () {
            Route::get('/', 'TesKesehatanController@index')->name('api.kesehatan');
        });
    });
});

resources/views/dashboard/admin.blade.php
<div class="row top_tiles">
    <div class="animated flipInY col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="tile-stats">
            <div class="icon"><i class="fa fa-edit"></i></div>
            <div class="count">{{ $dash_tot_pendaftaran }}</div>
            <h3>Daftar Peserta</h3>
            <p>Daftar seluruh peserta PMB</p>
        </div>
    </div>
    <div class="animated flipInY col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="tile-stats">
            <div class="icon"><i class="fa fa-check-square-o"></i></div>
            <div class="count">{{ $dash_tot_gugur }}</div>
            <h3>Peserta Gugur</h3>
            <p>Daftar peserta gugur administrasi</p>
        </div>
    </div>
    <div class="animated flipInY col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <div class="tile-stats">
            <div class="icon"><i class="fa fa-sign-in"></i></div>
            <div class="count">{{ $dash_tot_lolos }}</div>
            <h3>Peserta Lolos</h3>
            <p>Daftar peserta lolos administrasi</p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-7">
        <div class="x_panel">
            <div class="x_title">
                <h2>Hasil Verifikasi Dokumen <small>Grafik</small></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <canvas id="canvas1i" style="margin: 5px 10px 10px 0"></canvas>
            </div>
        </div>
    </div>
    <div class="col-md-5">
        <div class="x_panel">
            <div class="x_title">
                <h2>Hasil Verifikasi Dokumen <small>Per Institusi</small></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table class="table">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Nama Institusi</th>
                            <th>Lulus</th>
                            <th>Gugur</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php $no = 1; $tot_lolos = 0; $tot_gugur = 0; @endphp
                        @foreach($dash_verdok_institusi as $key => $value)
                            <tr>
                                <td>{{ $no }}</td>
                                <td>{{ $value['nama'] }}</td>
                                <td>{{ $value['lolos'] }}</td>
                                <td>{{ $value['gugur'] }}</td>
                                <td>{{ $value['lolos'] + $value['gugur']}}</td>
                            </tr>
                            @php $no++; $tot_lolos+=$value['lolos']; $tot_gugur+=$value['gugur']; @endphp
                        @endforeach
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="2">Total</td>
                        <td>{{ $tot_lolos }}</td>
                        <td>{{ $tot_gugur }}</td>
                        <td>{{ $tot_lolos + $tot_gugur }}</td>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

@section('js')
    <!-- Doughnut Chart -->
    <script>
        $(document).ready(function() {
            var canvasDoughnut,
                options = {
                    legend: {
                        display: true,
                        position: 'bottom',
                    },
                    responsive: true
                };

            new Chart(document.getElementById("canvas1i"), {
                type: 'doughnut',
                tooltipFillColor: "rgba(51, 51, 51, 0.55)",
                data: {
                    labels: [
                        "Lulus",
                        "Gugur"
                    ],
                    datasets: [{
                        data: [{{ $dash_tot_lolos }}, {{ $dash_tot_gugur }}],
                        backgroundColor: [
                            "#E95E4F",
                            "#9B59B6",
                        ],
                        hoverBackgroundColor: [
                            "#E74C3C",
                            "#B370CF",
                        ]

                    }]
                },
                options: options
            });
        });
    </script>
    <!-- /Doughnut Chart -->
@endsection

resources/views/dashboard/operator.blade.php
<div class="row">
    <div class="col-md-12">
        <h5>Institusi: <strong>{{ $institusi->nama }}</strong></h5>
    </div>
</div>
<div class="row">
    <div class="col-md-7">
        <div class="x_panel">
            <div class="x_title">
                <h2>Hasil Verifikasi Dokumen <small>Grafik</small></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <canvas id="canvas1i" style="margin: 5px 10px 10px 0"></canvas>
            </div>
        </div>
    </div>
    <div class="col-md-5">
        <div class="x_panel">
            <div class="x_title">
                <h2>Hasil Verifikasi Dokumen <small>Per Jurusan (Pilihan 1)</small></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table class="table">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Nama Jurusan</th>
                            <th>Lulus</th>
                            <th>Gugur</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php $no = 1; $tot_lolos = 0; $tot_gugur = 0; @endphp
                        @foreach($dash_verdok_jurusan as $key => $value)
                            <tr>
                                <td>{{ $no }}</td>
                                <td>{{ $value['nama'] }}</td>
                                <td>{{ $value['lolos'] }}</td>
                                <td>{{ $value['gugur'] }}</td>
                                <td>{{ $value['lolos'] + $value['gugur'] }}</td>
                            </tr>
                            @php $no++; $tot_lolos+=$value['lolos']; $tot_gugur+=$value['gugur']; @endphp
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="2">Total</td>
                            <td>{{ $tot_lolos }}</td>
                            <td>{{ $tot_gugur }}</td>
                            <td>{{ $tot_lolos + $tot_gugur }}</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

@section('js')
    <!-- Doughnut Chart -->
    <script>
        $(document).ready(function() {
            var canvasDoughnut,
                options = {
                    legend: {
                        display: true,
                        position: 'bottom',
                    },
                    responsive: true
                };

            new Chart(document.getElementById("canvas1i"), {
                type: 'doughnut',
                tooltipFillColor: "rgba(51, 51, 51, 0.55)",
                data: {
                    labels: [
                        "Lulus",
                        "Gugur"
                    ],
                    datasets: [{
                        data: [{{ $dash_verdok_institusi['lolos'] }}, {{ $dash_verdok_institusi['gugur'] }}],
                        backgroundColor: [
                            "#E95E4F",
                            "#9B59B6",
                        ],
                        hoverBackgroundColor: [
                            "#E74C3C",
                            "#B370CF",
                        ]

                    }]
                },
                options: options
            });
        });
    </script>
    <!-- /Doughnut Chart -->
@endsection

resources/views/dashboard/siswa.blade.php
<div class="row">
	<div class="col-md-7">
		<div class="x_panel">
			<div class="x_title">
				<h2>Resume Pendaftar</h2>
              	<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<table class="table table-striped table-bordered">
					<tr>
						<td>Nama Siswa</td>
						<td>{{ $data->nama }}</td>
					</tr>
					<tr>
						<td>NISN</td>
						<td>{{ $data->nisn }}</td>
					</tr>
					<tr>
						<td>Sekolah</td>
						<td>{{ $data->nama_sekolah }}</td>
					</tr>
					<tr>
						<td>Alamat</td>
						<td>{{ $data->alamat_sekolah }}</td>
					</tr>
					<tr>
						<td>Tahun Lulus</td>
						<td>{{ $data->tahun_lulus }}</td>
					</tr>
				</table>

				<table class="table table-striped table-bordered">
					<thead>
						<tr>
							<td colspan="2">Status Pendaftaran</td>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Finalisasi</td>
							<td>
								@if ( !$kelengkapan )
									<a href="{{ route('siswa.show', $data->id) }}">Cek kelengkapan data dan berkas dokumen pendaftaran</a>
								@else
									@if ( $state == '' )
										<a href="{{ route('pendaftaran.index') }}">Anda belum mendaftar, silahkan lakukan pendaftaran.</a>
									@else
										{{ $state }}
									@endif
								@endif
							</td>
						</tr>
						<tr>
							<td>Nomor Pendaftaran</td>
							<td>{{ $pendaftaran->no_pendaftaran ?? '-' }}</td>
						</tr>
						@if( $pendaftaran !== null)
						<tr>
							<td colspan="2">
								<a href="{{ route('siswa.kartu') }}" class="btn btn-success" target="_blank">
									Unduh Kartu Peserta
								</a>
							</td>
						</tr>
						@endif
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="col-md-5">
		<div class="x_panel">
			<div class="x_title">
				<h2>Jadwal Pendaftaran</h2>
              	<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<ul class="list-unstyled timeline">
					@foreach($jadwal as $key => $value)
					<li>
                        <div class="tags">
                        </div>
						<div class="block">
							<div class="block_content">
								<h2 class="title">
									@if ($value->tanggal_awal == $value->tanggal_akhir)
										<a>{{ date('d M Y', strtotime($value->tanggal_awal)) }}</a>
									@else
										<a>{{ date('d M Y', strtotime($value->tanggal_awal)) }} - {{ date('d M Y', strtotime($value->tanggal_akhir)) }}</a>
									@endif
								</h2>
								<p class="excerpt">{{ $value->nama }}</p>
							</div>
						</div>
					</li>
					@endforeach
				</ul>
			</div>
		</div>
	</div>
</div>