routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('frontend.index');
Route::get('jadwal-pmb', 'WelcomeController@jadwal')->name('frontend.jadwal');
Route::get('informasi-pendaftaran', 'WelcomeController@informasi')->name('frontend.informasi');
Route::get('brosur-pmb', 'WelcomeController@brosur')->name('frontend.brosur');
Route::get('dokumen-pmb', 'WelcomeController@dokumen')->name('frontend.dokumen');
Route::resource('post', 'PostController');

Route::get('/register-success', 'WelcomeController@register_success');
Route::get('/aktifasi', 'WelcomeController@aktifasi')->name('aktifasi');
Route::get('/aktifasi-resend', 'WelcomeController@aktifasi_resend')->name('aktifasi.resend');
Route::post('/aktifasi-send', 'WelcomeController@aktifasi_send')->name('aktifasi.send');
Route::get('/viewfile', 'ViewFileController@index')->name('viewfile');

Auth::routes();

Route::group(['middleware' => 'auth'], function ()
{
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/profile', 'HomeController@profile')->name('profile');
	Route::put('/profile/{id}/update', 'HomeController@update')->name('profile.update');

    Route::group(['middleware' => 'roles', 'roles' => 'administrator'], function ()
    {
		Route::get('admin', 'Admin\AdminController@index');
		Route::resource('admin/roles', 'Admin\RolesController');
		Route::resource('admin/permissions', 'Admin\PermissionsController');
		Route::resource('admin/users', 'Admin\UsersController');
		Route::resource('admin/pages', 'Admin\PagesController');
		Route::resource('admin/activitylogs', 'Admin\ActivityLogsController')->only([
		    'index', 'show', 'destroy'
		]);
		Route::resource('admin/settings', 'Admin\SettingsController');
		Route::get('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@getGenerator']);
		Route::post('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@postGenerator']);
		
		Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
	});

    Route::group(['middleware' => 'roles', 'roles' => ['siswa', 'admin_pusat']], function ()
    {
        Route::resource('siswa', 'SiswaController');
        Route::resource('pegawai', 'PegawaiController');
    });

    Route::group(['middleware' => 'roles', 'roles' => ['siswa', 'admin_pusat', 'operator']], function ()
    {
        Route::resource('pendaftaran', 'PendaftaranController');
    });

    Route::group(['middleware' => 'roles', 'roles' => ['admin_pusat', 'operator']], function ()
    {
        Route::get('list-pendaftaran', 'PendaftaranController@list')->name('pendaftaran.list');
    });

    Route::group(['middleware' => 'roles', 'roles' => 'siswa'], function ()
    {
		Route::get('pemilihan-jalur', 'PendaftaranController@jalur')->name('pilih-jalur');
		Route::post('jalur/simpan-jalur', 'PendaftaranController@store_jalur')->name('store-jalur');
		Route::get('jurusan/pemilihan-jurusan', 'PendaftaranController@jurusan')->name('pilih-jurusan');
		Route::post('jurusan/simpan-jurusan', 'PendaftaranController@store_jurusan')->name('store-jurusan');
		Route::resource('prestasi', 'PrestasiController');
		Route::get('resume', 'PendaftaranController@resume')->name('pendaftaran.resume');
        Route::get('siswa/kartu/cetak', 'SiswaController@kartu')->name('siswa.kartu');
	});

    Route::group(['middleware' => 'roles', 'roles' => 'admin_pusat'], function ()
    {
        Route::resource('tes-wawancara', 'WawancaraController');
        Route::get('tes-wawancara/download/pdf', 'WawancaraController@pdf')->name('tes-wawancara.pdf');
        Route::get('tes-wawancara/download/xls', 'WawancaraController@xls')->name('tes-wawancara.xls');
        Route::resource('tes-kesehatan', 'TesKesehatanController');
        Route::get('tes-kesehatan/download/pdf', 'TesKesehatanController@pdf')->name('tes-kesehatan.pdf');
        Route::get('tes-kesehatan/download/xls', 'TesKesehatanController@xls')->name('tes-kesehatan.xls');
        Route::resource('verifikasi-akhir', 'VerifikasiAkhirController');
        Route::post('verifikasi-akhir/generate', 'VerifikasiAkhirController@generate')->name('generate-jurusan');

        Route::resource('cms', 'ContentController');
		Route::resource('jadwal', 'JadwalController');
    });

    Route::group(['middleware' => 'roles', 'roles' => 'operator'], function ()
    {
        Route::resource('verifikasi-dokumen', 'VerifikasiDokumenController');
        Route::resource('tes-tulis', 'TesTulisController');
        Route::get('tes-tulis/download/pdf', 'TesTulisController@pdf')->name('tes-tulis.pdf');
        Route::get('tes-tulis/download/xls', 'TesTulisController@xls')->name('tes-tulis.xls');
    });

    Route::group(['namespace' => 'Api', 'prefix' => 'api'], function () {
        Route::group(['prefix' => '/siswa'], function () {
            Route::get('/', 'SiswaController@index')->name('api.siswa');
        });
        Route::group(['prefix' => '/verifikasi-dokumen'], function () {
            Route::get('/', 'VerifikasiDokumenController@index')->name('api.verifikasi');
        });
        Route::group(['prefix' => '/tes-tulis'], function () {
            Route::get('/', 'TesTulisController@index')->name('api.tulis');
        });
        Route::group(['prefix' => '/tes-wawancara'], function () {
            Route::get('/', 'WawancaraController@index')->name('api.wawancara');
        });
        Route::group(['prefix' => '/tes-kesehatan'], function () {
            Route::get('/', 'TesKesehatanController@index')->name('api.kesehatan');
        });
    });
});

resources/views/cms/brosur.blade.php
@extends('layouts.gentellela')

@section('content')
<!-- page content -->
<div class="right_col" role="main">
	<div class="row">
		<form id="form_update" method="post" action="{{ route('cms.store') }}" class="form-horizontal form-label-left" enctype="multipart/form-data">
			{{ csrf_field() }}

			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12 text-right">
						<button class="btn btn-app"><i class="fa fa-save"></i> Simpan</button>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="x_panel">
						<div class="x_title">
							<h2>Brosur PMB</h2>
							<div class="clearfix"></div>
						</div>
						<div class="x_content">
							<div class="dashboard-widget-content">
								<div class="col-md-12 hidden-small">
									<div class="form-group">
		                    			<label class="control-label col-sm-2">Upload Brosur</label>
		                    			<div class="col-sm-9">
		                        			<input type="file" id="brosur" class="form-control" name="konten[brosur-pmb]" required>
		                    			</div>
		                			</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="x_panel">
						<div class="x_title">
							<h2>Preview Brosur</h2>
							<div class="clearfix"></div>
						</div>
						<div class="x_content">
							<div class="dashboard-widget-content">
								<div class="col-md-12 hidden-small">
									<img src="{{ route('viewfile') . '?file=' . $brosur }}" width="100%" height="auto">
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
</div>
<!-- /page content -->
@endsection

@section('js')
@if( Session::has('success') )
<script type="text/javascript">
	swal("Berhasil", "{{ Session::get('success') }}", "success");
</script>
@endif
@if( $errors->any() )
<script type="text/javascript">
	swal("Tidak dapat menyimpan data", "{{ Html::ul($errors->all()) }}", "error");
</script>
@endif
@endsection

resources/views/cms/dokumen.blade.php
@extends('layouts.gentellela')

@section('content')
<!-- page content -->
<div class="right_col" role="main">
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="row">
				<div class="col-md-12 col-sm-12 col-xs-12 text-right">
					<button
					class="btn btn-app"
					data-toggle="modal"
					data-target="#modal_add">
					<i class="fa fa-plus"></i> Tambah
				</button>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>Daftar Dokumen Persyaratan PMB</h2>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<div class="dashboard-widget-content">
							<div class="col-md-12 hidden-small">
								<table id="datatable-fixed-header" class="table table-striped table-bordered">
									<thead>
										<tr>
											<th>Nama</th>
											<th width="40px">Lihat</th>
											<th width="40px">Action</th>
										</tr>
									</thead>
									<tbody>
										@foreach($dokumen as $key => $value)
										<tr>
											<td>{{ $value->dokumen['nama'] }}</td>
											<td><a class="btn btn-default" href="{{ route('viewfile') . '?file=' . $value->dokumen['file'] }}" target="_blank"><i class="fa fa-search"></i></a></td>
											<td>
												<a
	  											href="{{ route('cms.destroy', $value->id) }}"
	  											class="btn btn-danger helper"
	  											title="Hapus Dokumen"
	  											data-method="delete"
	  											data-id="{{ $value->id }}"
	  											data-token="{{ csrf_token() }}">
	  												<i class="fa fa-trash" ></i>
	  											</a>
	  										</td>
										</tr>
										@endforeach
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>

<div id="modal_add" class="modal fade" role="dialog">
	<div class="modal-dialog modal-lg">
		<!-- Modal content-->
		<form action="{{ route('cms.store') }}" id="form_add" method="post" class="modal-content" enctype="multipart/form-data">
			{{ csrf_field() }}

			<div class="modal-header bg-primary-600">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Upload Dokumen</h4>
			</div>
			<div class="modal-body form-horizontal">
				<div class="form-group">
					<label class="control-label col-sm-3">Nama Dokumen</label>
					<div class="col-sm-9">
						<input type="text" id="nama_add" class="form-control" name="konten[dokumen-pmb][nama]" required>
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-sm-3">File Dokumen</label>
					<div class="col-sm-9">
						<input type="file" id="file_add" class="form-control" name="konten[dokumen-pmb][file]" required>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-danger" data-dismiss="modal"><b><i class="fa fa-close"></b></i> Batal</button>
				<button type="submit" class="btn btn-success"><b><i class="fa fa-save"></i></b> Simpan</button>
			</div>
		</form>
	</div>
</div>

<!-- /page content -->
@endsection

@section('js')
@if( Session::has('success') )
<script type="text/javascript">
	swal("Berhasil", "{{ Session::get('success') }}", "success");
</script>
@endif
@if( $errors->any() )
<script type="text/javascript">
	swal("Tidak dapat menyimpan data", "{{ Html::ul($errors->all()) }}", "error");
</script>
@endif

</script>
<script>
	$(document).ready(function(){
		$('#datatable-fixed-header').DataTable({
			fixedHeader: true
		});
        $.ajax({
            url: "{{ asset('js/helper.js') }}", dataType: "script",
        });

		var handleDataTableButtons = function() {
			if ($("#datatable-buttons").length) {
				$("#datatable-buttons").DataTable({
					dom: "Bfrtip",
					buttons: [
					{
						extend: "csv",
						className: "btn-sm"
					},
					{
						extend: "excel",
						className: "btn-sm"
					},
					{
						extend: "pdf",
						className: "btn-sm"
					},
					],
					responsive: true
				});
			}
		};

		TableManageButtons = function() {
			"use strict";
			return {
				init: function() {
					handleDataTableButtons();
				}
			};
		}();

		TableManageButtons.init();
	});
</script>
@endsection

resources/views/cms/homepage.blade.php
@extends('layouts.gentellela')

@section('content')
<!-- page content -->
<div class="right_col" role="main">
	<div class="row">
		<form id="form_update" method="post" action="{{ route('cms.store') }}" class="form-horizontal form-label-left">
			{{ csrf_field() }}

			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12 text-right">
						<button class="btn btn-app"><i class="fa fa-save"></i> Simpan</button>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="x_panel">
						<div class="x_title">
							<h2>Pengaturan Konten Homepage</h2>
							<div class="clearfix"></div>
						</div>
						<div class="x_content">
							<div class="dashboard-widget-content">
								<div class="col-md-12 hidden-small">
									<div class="form-group">
		                    			<label class="control-label col-sm-2">Judul</label>
		                    			<div class="col-sm-9">
		                        			<input type="text" id="judul" class="form-control" name="konten[judul]" value="{{ $judul }}">
		                    			</div>
		                			</div>
									<div class="form-group">
		                    			<label class="control-label col-sm-2">Sub Judul</label>
		                    			<div class="col-sm-9">
		                        			<input type="text" id="sub_judul" class="form-control" name="konten[sub-judul]" value="{{ $sub }}">
		                    			</div>
		                			</div>
									<div class="form-group">
		                    			<label class="control-label col-sm-2">Deskripsi</label>
		                    			<div class="col-sm-9">
		                        			<input type="text" id="deskripsi" class="form-control" name="konten[deskripsi]" value="{{ $deskripsi }}">
		                    			</div>
		                			</div>
									<div class="form-group">
		                    			<label class="control-label col-sm-2">Tanggal Countdown</label>
		                    			<div class="col-sm-9">
		                        			<input type="date" id="countdown" class="form-control" name="konten[countdown]" value="{{ $countdown }}">
		                    			</div>
		                			</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="x_panel">
						<div class="x_title">
							<h2>Informasi Kontak</h2>
							<div class="clearfix"></div>
						</div>
						<div class="x_content">
							<div class="dashboard-widget-content">
								<div class="col-md-12 hidden-small">
									<div class="form-group">
		                    			<label class="control-label col-sm-2">Alamat</label>
		                    			<div class="col-sm-9">
		                        			<input type="text" id="alamat" class="form-control" name="konten[alamat]" value="{{ $alamat }}">
		                    			</div>
		                			</div>
									<div class="form-group">
		                    			<label class="control-label col-sm-2">No. Telepon</label>
		                    			<div class="col-sm-9">
		                        			<input type="text" id="no_telepon" class="form-control" name="konten[no-telepon]" value="{{ $telepon }}">
		                    			</div>
		                			</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
</div>
<!-- /page content -->
@endsection

@section('js')
@if( Session::has('success') )
<script type="text/javascript">
	swal("Berhasil", "{{ Session::get('success') }}", "success");
</script>
@endif
@if( $errors->any() )
<script type="text/javascript">
	swal("Tidak dapat menyimpan data", "{{ Html::ul($errors->all()) }}", "error");
</script>
@endif
@endsection

resources/views/cms/informasi.blade.php
@extends('layouts.gentellela')

@section('content')
<!-- page content -->
<div class="right_col" role="main">
	<div class="row">
		<form id="form_update" method="post" action="{{ route('cms.store') }}" class="form-horizontal form-label-left" enctype="multipart/form-data">
			{{ csrf_field() }}

			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12 text-right">
						<button class="btn btn-app"><i class="fa fa-save"></i> Simpan</button>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="x_panel">
						<div class="x_title">
							<h2>Informasi PMB</h2>
							<div class="clearfix"></div>
						</div>
						<div class="x_content">
							<div class="dashboard-widget-content">
								<div class="col-md-12 hidden-small">
									<div class="form-group">
		                    			<div class="col-sm-12">
		                        			<textarea id="wysiwyg" class="wysiwyg" name="konten[informasi-pendaftaran]" required>{!! $informasi !!}</textarea>
		                    			</div>
		                			</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
</div>
<!-- /page content -->
@endsection

@section('js')
	<script src="{{ asset('/vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('/vendor/unisharp/laravel-ckeditor/adapters/jquery.js') }}"></script>
	
	@if( Session::has('success') )
		<script type="text/javascript">
			swal("Berhasil", "{{ Session::get('success') }}", "success");
		</script>
	@endif
	@if( $errors->any() )
		<script type="text/javascript">
			swal("Tidak dapat menyimpan data", "{{ Html::ul($errors->all()) }}", "error");
		</script>
	@endif

	<script type="text/javascript">
	    $(document).ready(function(){
	    	$('.wysiwyg').ckeditor({
	    		filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
    			filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=' + $("input[name=_token]").val(),
    			filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
	    		filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token=' + $("input[name=_token]").val()
	    	});

	    	CKEDITOR.editorConfig = function( config ) {
				config.toolbar = [
					{ name: 'document', items: [ 'Source', '-', 'Save', 'Preview', 'Print'] },
					{ name: 'clipboard', items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] },
					{ name: 'editing', items: [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ] },
					'/',
					{ name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript' ] },
					{ name: 'paragraph', items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ] },
					{ name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
					{ name: 'insert', items: [ 'Image', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak' ] },
					'/',
					{ name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] },
					{ name: 'colors', items: [ 'TextColor', 'BGColor' ] },
					{ name: 'tools', items: [ 'Maximize', 'ShowBlocks' ] },
					{ name: 'about', items: [ 'About' ] }
				];
			};			
	    });
	</script>
@endsection