routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('frontend.index');
Route::get('jadwal-pmb', 'WelcomeController@jadwal')->name('frontend.jadwal');
Route::get('informasi-pendaftaran', 'WelcomeController@informasi')->name('frontend.informasi');
Route::get('brosur-pmb', 'WelcomeController@brosur')->name('frontend.brosur');
Route::get('dokumen-pmb', 'WelcomeController@dokumen')->name('frontend.dokumen');
Route::resource('post', 'PostController');

Route::get('/register-success', 'WelcomeController@register_success');
Route::get('/aktifasi', 'WelcomeController@aktifasi')->name('aktifasi');
Route::get('/aktifasi-resend', 'WelcomeController@aktifasi_resend')->name('aktifasi.resend');
Route::post('/aktifasi-send', 'WelcomeController@aktifasi_send')->name('aktifasi.send');
Route::get('/viewfile', 'ViewFileController@index')->name('viewfile');

Auth::routes();

Route::group(['middleware' => 'auth'], function ()
{
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/profile', 'HomeController@profile')->name('profile');
	Route::put('/profile/{id}/update', 'HomeController@update')->name('profile.update');

    Route::group(['middleware' => 'roles', 'roles' => 'administrator'], function ()
    {
		Route::get('admin', 'Admin\AdminController@index');
		Route::resource('admin/roles', 'Admin\RolesController');
		Route::resource('admin/permissions', 'Admin\PermissionsController');
		Route::resource('admin/users', 'Admin\UsersController');
		Route::resource('admin/pages', 'Admin\PagesController');
		Route::resource('admin/activitylogs', 'Admin\ActivityLogsController')->only([
		    'index', 'show', 'destroy'
		]);
		Route::resource('admin/settings', 'Admin\SettingsController');
		Route::get('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@getGenerator']);
		Route::post('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@postGenerator']);
		
		Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
	});

    Route::group(['middleware' => 'roles', 'roles' => ['siswa', 'admin_pusat']], function ()
    {
        Route::resource('siswa', 'SiswaController');
        Route::resource('pegawai', 'PegawaiController');
    });

    Route::group(['middleware' => 'roles', 'roles' => ['siswa', 'admin_pusat', 'operator']], function ()
    {
        Route::resource('pendaftaran', 'PendaftaranController');
    });

    Route::group(['middleware' => 'roles', 'roles' => ['admin_pusat', 'operator']], function ()
    {
        Route::get('list-pendaftaran', 'PendaftaranController@list')->name('pendaftaran.list');
    });

    Route::group(['middleware' => 'roles', 'roles' => 'siswa'], function ()
    {
		Route::get('pemilihan-jalur', 'PendaftaranController@jalur')->name('pilih-jalur');
		Route::post('jalur/simpan-jalur', 'PendaftaranController@store_jalur')->name('store-jalur');
		Route::get('jurusan/pemilihan-jurusan', 'PendaftaranController@jurusan')->name('pilih-jurusan');
		Route::post('jurusan/simpan-jurusan', 'PendaftaranController@store_jurusan')->name('store-jurusan');
		Route::resource('prestasi', 'PrestasiController');
		Route::get('resume', 'PendaftaranController@resume')->name('pendaftaran.resume');
        Route::get('siswa/kartu/cetak', 'SiswaController@kartu')->name('siswa.kartu');
	});

    Route::group(['middleware' => 'roles', 'roles' => 'admin_pusat'], function ()
    {
        Route::resource('tes-wawancara', 'WawancaraController');
        Route::get('tes-wawancara/download/pdf', 'WawancaraController@pdf')->name('tes-wawancara.pdf');
        Route::get('tes-wawancara/download/xls', 'WawancaraController@xls')->name('tes-wawancara.xls');
        Route::resource('tes-kesehatan', 'TesKesehatanController');
        Route::get('tes-kesehatan/download/pdf', 'TesKesehatanController@pdf')->name('tes-kesehatan.pdf');
        Route::get('tes-kesehatan/download/xls', 'TesKesehatanController@xls')->name('tes-kesehatan.xls');
        Route::resource('verifikasi-akhir', 'VerifikasiAkhirController');
        Route::post('verifikasi-akhir/generate', 'VerifikasiAkhirController@generate')->name('generate-jurusan');

        Route::resource('cms', 'ContentController');
		Route::resource('jadwal', 'JadwalController');
    });

    Route::group(['middleware' => 'roles', 'roles' => 'operator'], function ()
    {
        Route::resource('verifikasi-dokumen', 'VerifikasiDokumenController');
        Route::resource('tes-tulis', 'TesTulisController');
        Route::get('tes-tulis/download/pdf', 'TesTulisController@pdf')->name('tes-tulis.pdf');
        Route::get('tes-tulis/download/xls', 'TesTulisController@xls')->name('tes-tulis.xls');
    });

    Route::group(['namespace' => 'Api', 'prefix' => 'api'], function () {
        Route::group(['prefix' => '/siswa'], function () {
            Route::get('/', 'SiswaController@index')->name('api.siswa');
        });
        Route::group(['prefix' => '/verifikasi-dokumen'], function () {
            Route::get('/', 'VerifikasiDokumenController@index')->name('api.verifikasi');
        });
        Route::group(['prefix' => '/tes-tulis'], function () {
            Route::get('/', 'TesTulisController@index')->name('api.tulis');
        });
        Route::group(['prefix' => '/tes-wawancara'], function () {
            Route::get('/', 'WawancaraController@index')->name('api.wawancara');
        });
        Route::group(['prefix' => '/tes-kesehatan'], function () {
            Route::get('/', 'TesKesehatanController@index')->name('api.kesehatan');
        });
    });
});

app/Jadwal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Jadwal extends Model
{
    use SoftDeletes;

    protected $guarded = [];
}

app/Http/Controllers/JadwalController.php
<?php

namespace App\Http\Controllers;

use App\Libs\Services\JadwalService;
use Illuminate\Http\Request;

class JadwalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(JadwalService $service)
    {
    	$data = $service->getJadwal();

        return view('jadwal.index', ['data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, JadwalService $service)
    {
        $data = $request->except('_token');
        $service->createJadwal($data);

        return redirect()->to('jadwal')->withSuccess('Data jadwal berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id, JadwalService $service)
    {
        $data = $request->except(['_token', '_method']);
        $service->updateJadwal($id, $data);

        return redirect()->to('jadwal')->withSuccess('Data jadwal berhasil dirubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, JadwalService $service)
    {
        $service->deleteJadwal($id);
        return redirect()->to('jadwal')->withSuccess('Data jadwal berhasil dihapus');
    }
}

resources/views/jadwal/index.blade.php
@extends('layouts.gentellela')

@section('content')
<!-- page content -->
<div class="right_col" role="main">
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="row">
				<div class="col-md-12 col-sm-12 col-xs-12 text-right">
					<button
					class="btn btn-app"
					data-toggle="modal"
					data-target="#modal_add">
					<i class="fa fa-plus"></i> Tambah
				</button>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>Daftar Jadwal</h2>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<div class="dashboard-widget-content">
							<div class="col-md-12 hidden-small">
								<table id="datatable-fixed-header" class="table table-striped table-bordered">
									<thead>
										<tr>
											<th>Nama</th>
											<th>Tanggal Awal</th>
											<th>Tanggal Akhir</th>
											<th width="100px">Action</th>
										</tr>
									</thead>
									<tbody>
										@foreach($data as $key => $value)
										<tr>
											<td>{{ $value->nama }}</td>
											<td>{{ $value->tanggal_awal }}</td>
											<td>{{ $value->tanggal_akhir }}</td>
											<td>
												<a
	  											class="btn btn-default"
												title="Ubah Data"
												data-toggle="modal"
												data-target="#modal_update"
												data-url="{{ route('jadwal.update', $value->id) }}"
												data-nama="{{ $value->nama }}"
												data-awal="{{ $value->tanggal_awal }}"
												data-akhir="{{ $value->tanggal_akhir }}">
													<i class="fa fa-edit"></i>
												</a>
												<a
	  											href="{{ route('jadwal.destroy', $value->id) }}"
	  											class="btn btn-danger helper"
	  											title="Hapus Data"
	  											data-method="delete"
	  											data-id="{{ $value->id }}"
	  											data-token="{{ csrf_token() }}">
	  												<i class="fa fa-trash" ></i>
	  											</a>
	  										</td>
										</tr>
										@endforeach
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>

<div id="modal_add" class="modal fade" role="dialog">
	<div class="modal-dialog modal-lg">
		<!-- Modal content-->
		<form action="{{ route('jadwal.store') }}" id="form_add" method="post" class="modal-content">
			{{ csrf_field() }}

			<div class="modal-header bg-primary-600">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Jadwal Baru</h4>
			</div>
			<div class="modal-body form-horizontal">
				<div class="form-group">
					<label class="control-label col-sm-3">Keterangan*</label>
					<div class="col-sm-9">
						<input type="text" id="nama_add" required class="form-control" name="nama" value="{{ old('nama') }}">
					</div>
				</div>
			</div>
			<div class="modal-body form-horizontal">
				<div class="form-group">
					<label class="control-label col-sm-3">Tanggal Awal*</label>
					<div class="col-sm-9">
						<input type="date" id="tanggal_awal_add" required class="form-control" name="tanggal_awal" value="{{ old('tanggal_awal') }}">
					</div>
				</div>
			</div>
			<div class="modal-body form-horizontal">
				<div class="form-group">
					<label class="control-label col-sm-3">Tanggal Akhir*</label>
					<div class="col-sm-9">
						<input type="date" id="tanggal_akhir_add" required class="form-control" name="tanggal_akhir" value="{{ old('tanggal_akhir') }}">
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-danger" data-dismiss="modal"><b><i class="fa fa-close"></b></i> Batal</button>
				<button type="submit" class="btn btn-success"><b><i class="fa fa-save"></i></b> Simpan</button>
			</div>
		</form>
	</div>
</div>

<div id="modal_update" class="modal fade" role="dialog">
	<div class="modal-dialog modal-lg">
		<!-- Modal content-->
		<form action="" id="form_update" method="post" class="modal-content">
			{{ csrf_field() }}
			<input type="hidden" name="_method" value="put">

			<div class="modal-header bg-primary-600">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Perubahan Jadwal</h4>
			</div>
			<div class="modal-body form-horizontal">
				<div class="form-group">
					<label class="control-label col-sm-3">Keterangan*</label>
					<div class="col-sm-9">
						<input type="text" id="nama_update" required class="form-control" name="nama">
					</div>
				</div>
				<div class="modal-body form-horizontal">
					<div class="form-group">
						<label class="control-label col-sm-3">Tanggal Awal*</label>
						<div class="col-sm-9">
							<input type="date" id="tanggal_awal_update" required class="form-control" name="tanggal_awal">
						</div>
					</div>
				</div>
				<div class="modal-body form-horizontal">
					<div class="form-group">
						<label class="control-label col-sm-3">Tanggal Akhir*</label>
						<div class="col-sm-9">
							<input type="date" id="tanggal_akhir_update" required class="form-control" name="tanggal_akhir">
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-danger" data-dismiss="modal"><b><i class="fa fa-close"></b></i> Batal</button>
				<button type="submit" class="btn btn-success"><b><i class="fa fa-save"></i></b> Simpan</button>
			</div>
		</form>
	</div>
</div>
<!-- /page content -->
@endsection

@section('js')
@if( Session::has('success') )
<script type="text/javascript">
	swal("Berhasil", "{{ Session::get('success') }}", "success");
</script>
@endif
@if( $errors->any() )
<script type="text/javascript">
	swal("Tidak dapat menyimpan data", "{{ Html::ul($errors->all()) }}", "error");
</script>
@endif

</script>
<script>
	$(document).ready(function(){
		$('#datatable-fixed-header').DataTable({
			fixedHeader: true,
			ordering: false
		});
        $.ajax({
            url: "{{ asset('js/helper.js') }}", dataType: "script",
        });
	});

	$('#modal_update').on('show.bs.modal', function(e){
		$("#form_update").prop('action', $(e.relatedTarget).data('url'));
		$("#nama_update").val($(e.relatedTarget).data('nama'));
		$("#tanggal_awal_update").val($(e.relatedTarget).data('awal'));
		$("#tanggal_akhir_update").val($(e.relatedTarget).data('akhir'));
	});

</script>
@endsection