routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('frontend.index');
Route::get('jadwal-pmb', 'WelcomeController@jadwal')->name('frontend.jadwal');
Route::get('informasi-pendaftaran', 'WelcomeController@informasi')->name('frontend.informasi');
Route::get('brosur-pmb', 'WelcomeController@brosur')->name('frontend.brosur');
Route::get('dokumen-pmb', 'WelcomeController@dokumen')->name('frontend.dokumen');
Route::resource('post', 'PostController');

Route::get('/register-success', 'WelcomeController@register_success');
Route::get('/aktifasi', 'WelcomeController@aktifasi')->name('aktifasi');
Route::get('/aktifasi-resend', 'WelcomeController@aktifasi_resend')->name('aktifasi.resend');
Route::post('/aktifasi-send', 'WelcomeController@aktifasi_send')->name('aktifasi.send');
Route::get('/viewfile', 'ViewFileController@index')->name('viewfile');

Auth::routes();

Route::group(['middleware' => 'auth'], function ()
{
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/profile', 'HomeController@profile')->name('profile');
	Route::put('/profile/{id}/update', 'HomeController@update')->name('profile.update');

    Route::group(['middleware' => 'roles', 'roles' => 'administrator'], function ()
    {
		Route::get('admin', 'Admin\AdminController@index');
		Route::resource('admin/roles', 'Admin\RolesController');
		Route::resource('admin/permissions', 'Admin\PermissionsController');
		Route::resource('admin/users', 'Admin\UsersController');
		Route::resource('admin/pages', 'Admin\PagesController');
		Route::resource('admin/activitylogs', 'Admin\ActivityLogsController')->only([
		    'index', 'show', 'destroy'
		]);
		Route::resource('admin/settings', 'Admin\SettingsController');
		Route::get('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@getGenerator']);
		Route::post('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@postGenerator']);
		
		Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
	});

    Route::group(['middleware' => 'roles', 'roles' => ['siswa', 'admin_pusat']], function ()
    {
        Route::resource('siswa', 'SiswaController');
        Route::resource('pegawai', 'PegawaiController');
    });

    Route::group(['middleware' => 'roles', 'roles' => ['siswa', 'admin_pusat', 'operator']], function ()
    {
        Route::resource('pendaftaran', 'PendaftaranController');
    });

    Route::group(['middleware' => 'roles', 'roles' => ['admin_pusat', 'operator']], function ()
    {
        Route::get('list-pendaftaran', 'PendaftaranController@list')->name('pendaftaran.list');
    });

    Route::group(['middleware' => 'roles', 'roles' => 'siswa'], function ()
    {
		Route::get('pemilihan-jalur', 'PendaftaranController@jalur')->name('pilih-jalur');
		Route::post('jalur/simpan-jalur', 'PendaftaranController@store_jalur')->name('store-jalur');
		Route::get('jurusan/pemilihan-jurusan', 'PendaftaranController@jurusan')->name('pilih-jurusan');
		Route::post('jurusan/simpan-jurusan', 'PendaftaranController@store_jurusan')->name('store-jurusan');
		Route::resource('prestasi', 'PrestasiController');
		Route::get('resume', 'PendaftaranController@resume')->name('pendaftaran.resume');
        Route::get('siswa/kartu/cetak', 'SiswaController@kartu')->name('siswa.kartu');
	});

    Route::group(['middleware' => 'roles', 'roles' => 'admin_pusat'], function ()
    {
        Route::resource('tes-wawancara', 'WawancaraController');
        Route::get('tes-wawancara/download/pdf', 'WawancaraController@pdf')->name('tes-wawancara.pdf');
        Route::get('tes-wawancara/download/xls', 'WawancaraController@xls')->name('tes-wawancara.xls');
        Route::resource('tes-kesehatan', 'TesKesehatanController');
        Route::get('tes-kesehatan/download/pdf', 'TesKesehatanController@pdf')->name('tes-kesehatan.pdf');
        Route::get('tes-kesehatan/download/xls', 'TesKesehatanController@xls')->name('tes-kesehatan.xls');
        Route::resource('verifikasi-akhir', 'VerifikasiAkhirController');
        Route::post('verifikasi-akhir/generate', 'VerifikasiAkhirController@generate')->name('generate-jurusan');

        Route::resource('cms', 'ContentController');
		Route::resource('jadwal', 'JadwalController');
    });

    Route::group(['middleware' => 'roles', 'roles' => 'operator'], function ()
    {
        Route::resource('verifikasi-dokumen', 'VerifikasiDokumenController');
        Route::resource('tes-tulis', 'TesTulisController');
        Route::get('tes-tulis/download/pdf', 'TesTulisController@pdf')->name('tes-tulis.pdf');
        Route::get('tes-tulis/download/xls', 'TesTulisController@xls')->name('tes-tulis.xls');
    });

    Route::group(['namespace' => 'Api', 'prefix' => 'api'], function () {
        Route::group(['prefix' => '/siswa'], function () {
            Route::get('/', 'SiswaController@index')->name('api.siswa');
        });
        Route::group(['prefix' => '/verifikasi-dokumen'], function () {
            Route::get('/', 'VerifikasiDokumenController@index')->name('api.verifikasi');
        });
        Route::group(['prefix' => '/tes-tulis'], function () {
            Route::get('/', 'TesTulisController@index')->name('api.tulis');
        });
        Route::group(['prefix' => '/tes-wawancara'], function () {
            Route::get('/', 'WawancaraController@index')->name('api.wawancara');
        });
        Route::group(['prefix' => '/tes-kesehatan'], function () {
            Route::get('/', 'TesKesehatanController@index')->name('api.kesehatan');
        });
    });
});

app/Http/Controllers/PendaftaranController.php
<?php

namespace App\Http\Controllers;

use App\Jurusan;
use App\Libs\Services\InstitusiService;
use App\Libs\Services\PendaftaranDetailService;
use App\Libs\Services\PendaftaranService;
use App\Libs\Services\PrestasiService;
use App\Libs\Services\SerialNumberService;
use App\Libs\Services\VerifikasiDetailService;
use App\Libs\Services\VerifikasiPendaftaranService;
use App\Libs\Traits\InfoPendaftaran;
use App\Libs\Traits\InfoSiswa;
use App\Libs\Traits\InstitusiJurusan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Redirect;

class PendaftaranController extends Controller
{
    use InfoSiswa, InfoPendaftaran, InstitusiJurusan;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(PendaftaranService $service)
    {
        $pendaftaran = [];
        $access = $this->cekKelengkapanDokumen();

        if ($access) {
            $pendaftaran = $this->getPendaftaran();

            if ($pendaftaran !== null) {
                $pendaftaran['jalur_label'] = ucwords(str_replace("-", " ", $pendaftaran->jalur));
            }
        }

        return view('pendaftaran.index', [
            'access' => $access,
            'data' => $pendaftaran
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request, PendaftaranService $service)
    {
        $this->validate($request, [
            'jalur' => 'required'
        ]);

        $service->createPendaftaran([
            'siswa_id' => $user = auth()->user()->person_id,
            'jalur' => $request->jalur
        ]);

        return redirect()->route('pilih-jalur');
    }

    /**
     * @param Request $request
     * @param PendaftaranService $service
     * @return mixed
     * @throws \Throwable
     */
    public function store(Request $request,
                          PendaftaranService $service,
                          SerialNumberService $sService)
    {
        $pendaftaran = $this->getPendaftaran();

        DB::transaction(function () use ($pendaftaran, $service, $sService) {
            $no_pendaftaran = $sService->getSerialNumber($pendaftaran->institusi);

            $service->updatePendaftaran($pendaftaran->id, ['no_pendaftaran' => $no_pendaftaran]);

            $this->updateState($pendaftaran->id, 'menyelesaikan_pendaftaran');
        });

        return Redirect::to('pendaftaran')->withSuccess('Pendaftaran berhasil disubmit');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id,
                         PendaftaranService $service,
                         PendaftaranDetailService $dService,
                         PrestasiService $pService)
    {
        $pendaftaran = $service->getPendaftaranById($id);
        $pendaftaran['jalur_label'] = ucwords(str_replace("-", " ", $pendaftaran->jalur));
        $pendaftaran['jurusan_1_label'] = Jurusan::selectName($pendaftaran->jurusan_1);
        $pendaftaran['jurusan_2_label'] = Jurusan::selectName($pendaftaran->jurusan_2);

        $detail = $dService->getPendaftaranDetailByPendaftaran($pendaftaran->id);
        $biodata = $detail->map(function($item) {
            return $item;
        })->where('kelompok', 'biodata');

        $dokumen = $detail->map(function($item) {
            return $item;
        })->where('kelompok', 'berkas');

        $cek_sistem_false = $detail->map(function($item) {
            return $item;
        })->where('cek_sistem', false)->count();

        $prestasi = $pService->getPrestasiByPendaftaran($pendaftaran->id);

        return view('pendaftaran.show', [
            'pendaftaran' => $pendaftaran,
            'biodata' => $biodata,
            'dokumen' => $dokumen,
            'cek_sistem_false' => $cek_sistem_false,
            'prestasi' => $prestasi
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, PendaftaranService $service)
    {
        $service->updatePendaftaran($id, ['state' => 'cancel']);

        return Redirect::to('pendaftaran');
    }

    /**
     * @param PrestasiService $service
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function jalur(PrestasiService $service)
    {
        $pendaftaran = $this->getPendaftaran();

        if ($pendaftaran->state != 'start') {
            return Redirect::to('pendaftaran')->withError('Anda tidak dapat memilih jalur');
        }

        $view = 'jalur-' . $pendaftaran->jalur;
        $jalur = str_replace("-", " ", $pendaftaran->jalur);
        $title = "Pendaftaran Calon Mahasiswa Baru Jalur " . ucwords($jalur);

        $prestasi = $service->getPrestasiByPendaftaran($pendaftaran->id);

        return view('pendaftaran.jalur', [
            'title' => $title,
            'view' => $view,
            'prestasi' => $prestasi
        ]);
    }

    /**
     * @param Request $request
     * @param PendaftaranService $service
     * @param PendaftaranDetailService $dService
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store_jalur(Request $request, PendaftaranService $service,
                                PendaftaranDetailService $dService)
    {
        $rollback = false; $keterangan = '';
        $siswa = $request->user()->person;
        $pendaftaran = $this->getPendaftaran();

        DB::beginTransaction();
        //insert data siswa ke pendaftaran detail
        foreach ($siswa->toArray() as $key => $value) {
            if ($key != 'id' && $key != 'created_at' && $key != 'updated_at') {
                $cek_sistem = true;
                if ($value == null){
                    $value = '';
                }
                $keterangan = $this->cekPersyaratan($siswa, $pendaftaran->jalur, $key, $value);

                if ($keterangan != '') {
                    $cek_sistem = false;
                    if ($pendaftaran->jalur == 'undangan-petani' ||
                        $pendaftaran->jalur == 'undangan-smk') {
                    } else {
                        $rollback = true;
                        break;
                    }
                }

                $dService->createPendaftaranDetail([
                    'pendaftaran_id' => $pendaftaran->id,
                    'key' => $key,
                    'value' => $value,
                    'cek_sistem' => $cek_sistem,
                    'cek_admin' => true,
                    'keterangan' => $keterangan,
                    'kelompok' => 'biodata'
                ]);
            }
        }

        if ($rollback) {
            DB::rollBack();
            return Redirect::to('pendaftaran')->withError($keterangan);
        }

        //insert dokumen ke pendaftaran detail
        $data = $request->except(['_token']);
        foreach ($data as $key => $value) {
            $cek_sistem = true;
            if ($value == null){
                $value = '';
            }

            $keterangan = $this->cekPersyaratan($siswa, $pendaftaran->jalur, $key, $value);

            if ($keterangan != '') {
                $cek_sistem = false;
            }

            if ( $request->hasFile($key) ) {
                $value = $request->file($key)->store("pendaftaran");
            }

            $dService->createPendaftaranDetail([
                'pendaftaran_id' => $pendaftaran->id,
                'key' => $key,
                'value' => $value,
                'cek_sistem' => $cek_sistem,
                'cek_admin' => true,
                'keterangan' => $keterangan,
                'kelompok' => 'berkas'
            ]);
        }

        $this->updateState($pendaftaran->id, 'menyelesaikan_pemberkasan');
        DB::commit();

        return redirect()->route('pilih-jurusan');
    }

    public function jurusan(InstitusiService $service)
    {
        $pendaftaran = $this->getPendaftaran();
        if ($pendaftaran->state != 'pemilihan_jurusan') {
            return Redirect::to('pendaftaran')->withError('Anda tidak dapat memilih jurusan');
        }

        $institusi = $service->getOnlyCabang();
        $jurusan = $this->getJurusan($institusi[0]->id);

        return view('pendaftaran.jurusan', [
            'institusi' => $institusi,
            'jurusan' => $jurusan
        ]);
    }

    /**
     * @param Request $request
     * @param PendaftaranService $service
     * @param PendaftaranDetailService $dService
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Throwable
     */
    public function store_jurusan(Request $request,
                                  PendaftaranService $service,
                                  PendaftaranDetailService $dService)
    {
        $data = $request->only(['institusi', 'jurusan_1', 'jurusan_2']);
        if ($data['jurusan_1'] == $data['jurusan_2']) {
            return redirect()->back()->withError('Jurusan tidak boleh sama');
        }

        $siswa = $request->user()->person;
        $pendaftaran = $this->getPendaftaran();
        DB::transaction(function () use ($data, $siswa, $pendaftaran, $service, $dService) {
            $cek_sistem = true;
            $keterangan = $this->cekJurusan($siswa, $data);

            if ($keterangan != '') {
                $cek_sistem = false;
            }

resources/views/pendaftaran/info.blade.php
<div class="col-md-12 col-sm-12 col-xs-12">
	<div class="x_panel">
		<div class="x_title">
			<h2>Informasi Pendaftaran</h2>
			<div class="clearfix"></div>
		</div>
		<div class="x_content">
            @include('pendaftaran.notifikasi')

			<form id="informasi_pendaftaran" class="form-horizontal form-label-left" action="{{ route('pendaftaran.destroy', $data->id) }}" method="post">
				<input type="hidden" name="_method" value="DELETE">

				{{ @csrf_field() }}

				<div class="form-group">
					<label class="control-label col-sm-2">Jalur Pendaftaran</label>
					<div class="col-sm-9">
						<input type="text" id="nama" class="form-control" value="{{ $data->jalur_label }}" readonly>
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-sm-2">Tanggal Mendaftar</label>
					<div class="col-sm-9">
						<input type="text" id="nama" class="form-control" value="{{ $data->created_at }}" readonly>
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-sm-2">Status</label>
					<div class="col-sm-9">
						<input type="text" id="nama" class="form-control" value="{{ ucwords(str_replace('_', ' ', $data->state)) }}" readonly>
					</div>
				</div>
				@if($data->state == 'start' ||
					$data->state == 'pemilihan_jurusan' ||
					$data->state == 'review_pendaftaran')
				<div class="form-group">
					<div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-2">
						<button type="submit" class="btn btn-danger">Batalkan Pendaftaran</button>
					</div>
				</div>
				@endif
			</form>
		</div>
	</div>
</div>

resources/views/pendaftaran/jalur.blade.php
@extends('layouts.gentellela')

@section('content')
<div class="right_col" role="main">
	<div class="">
		<div class="page-title">
			<div class="title_left">
				<h3></h3>
			</div>
		</div>

		<div class="clearfix"></div>

		<div class="row">
			@include('pendaftaran.' . $view)
		</div>

		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>Daftar Prestasi</h2>
						<ul class="nav navbar-right panel_toolbox">
							<li>
					  			<button class="btn btn-success"
					  				data-toggle="modal"
					  				data-target="#modal_add">
					  				<i class="fa fa-plus"></i> Tambah
					  			</button>
							</li>
						</ul>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<table id="datatable-fixed-header" class="table table-striped table-bordered">
							<thead>
								<tr>
									<th>Nama</th>
									<th>Tahun</th>
									<th>Tingkat</th>
									<th>Kepesertaan</th>
									<th>Prestasi</th>
									<th width="160px">Action</th>
								</tr>
							</thead>
							<tbody>
							@foreach( $prestasi as $key => $value )
								<tr>
									<td>{{ $value->nama }}</td>
									<td>{{ $value->tahun }}</td>
									<td>{{ $value->tingkat }}</td>
									<td>{{ $value->kepesertaan }}</td>
									<td>{{ $value->prestasi }}</td>
									<td>
										<form method="post" action="{{ route('prestasi.destroy', $value->id) }}">
											{{ csrf_field() }}

											<input type="hidden" name="_method" value="DELETE">

											<a href="{{ route('viewfile') . '?file=' . $value->bukti }}"
												target="_blank"
												class="btn btn-primary"><i class="fa fa-search"></i></a>
                            				<button type="button"
                            					class="btn btn-warning"
					  							data-toggle="modal"
					  							data-target="#modal_update"
												data-url="{{ route('prestasi.update', $value->id) }}"
					  							data-id="{{ $value->id }}"
					  							data-bidang="{{ $value->bidang }}"
					  							data-nama="{{ $value->nama }}"
					  							data-tahun="{{ $value->tahun }}"
					  							data-tingkat="{{ $value->tingkat }}"
					  							data-kepesertaan="{{ $value->kepesertaan }}"
					  							data-prestasi="{{ $value->prestasi }}">
				  								<i class="fa fa-pencil"></i>
					  						</button>

					  						<button type="submit" class="btn btn-danger">
					  							<i class="fa fa-trash"></i>
					  						</button>
										</form>
									</td>
								</tr>
							@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="modal_add" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <form action="{{ route('prestasi.store') }}" id="form_add" method="post" class="modal-content" enctype="multipart/form-data">
        	{{ csrf_field() }}

            <div class="modal-header bg-primary-600">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Tambah Data Prestasi</h4>
            </div>
            <div class="modal-body form-horizontal">
                <div class="form-group">
                    <label class="control-label col-sm-3">Bidang Prestasi*</label>
                    <div class="col-sm-9">
                    	<select id="bidang_add" class="form-control" name="bidang">
                    		<option value="Science & Teknologi">Science & Teknologi</option>
                    		<option value="Olah Raga">Olah Raga</option>
                    		<option value="Seni">Seni</option>
                    	</select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Nama Prestasi*</label>
                    <div class="col-sm-9">
                    	<input id="nama_add" type="text" class="form-control" name="nama" required>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Tahun*</label>
                    <div class="col-sm-9">
                    	<input id="tahun_add" type="text" class="form-control" name="tahun" required>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Tingkat*</label>
                    <div class="col-sm-9">
                    	<select id="tingkat_add" class="form-control" name="tingkat">
                    		<option value="Sekolah">Sekolah</option>
                    		<option value="Kecamatan">Kecamatan</option>
                    		<option value="Kabupaten">Kabupaten</option>
                    		<option value="Provinsi">Provinsi</option>
                    		<option value="Nasional">Nasional</option>
                    		<option value="Internasional">Internasional</option>
                    	</select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Kepesertaan*</label>
                    <div class="col-sm-9">
                    	<select id="kepesertaan_add" class="form-control" name="kepesertaan">
                    		<option value="Perorangan">Perorangan</option>
                    		<option value="Beregu">Beregu</option>
                    	</select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Prestasi*</label>
                    <div class="col-sm-9">
                    	<select id="prestasi_add" class="form-control" name="prestasi">
                    		<option value="Juara 1">Juara 1</option>
                    		<option value="Juara 2">Juara 2</option>
                    		<option value="Juara 3">Juara 3</option>
                    		<option value="Harapan 1">Harapan 1</option>
                    		<option value="Harapan 2">Harapan 2</option>
                    	</select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Bukti Prestasi*</label>
                    <div class="col-sm-9">
						<input type="file" id="bukti_add" class="form-control" name="bukti" accept=".jpg,.jpeg,.png,application/pdf" required>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"><b><i class="fa fa-close"></i></b> Batal</button>
                <button type="submit" class="btn btn-success"><b><i class="fa fa-save"></i></b> Simpan</button>
            </div>
        </form>
    </div>
</div>

<div id="modal_update" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
		<form action="" id="form_update" method="post" class="modal-content">
			{{ csrf_field() }}
			<input type="hidden" name="_method" value="put">

            <div class="modal-header bg-primary-600">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Tambah Data Prestasi</h4>
            </div>
            <div class="modal-body form-horizontal">
                <div class="form-group">
                    <label class="control-label col-sm-3">Bidang Prestasi*</label>
                    <div class="col-sm-9">
                    	<select id="bidang_update" class="form-control" name="bidang">
                    		<option value="Science & Teknologi">Science & Teknologi</option>
                    		<option value="Olah Raga">Olah Raga</option>
                    		<option value="Seni">Seni</option>
                    	</select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Nama Prestasi*</label>
                    <div class="col-sm-9">
                    	<input id="nama_update" type="text" class="form-control" name="nama" required>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Tahun*</label>
                    <div class="col-sm-9">
                    	<input id="tahun_update" type="text" class="form-control" name="tahun" required>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Tingkat*</label>
                    <div class="col-sm-9">
                    	<select id="tingkat_update" class="form-control" name="tingkat">
                    		<option value="Sekolah">Sekolah</option>
                    		<option value="Kecamatan">Kecamatan</option>
                    		<option value="Kabupaten">Kabupaten</option>
                    		<option value="Provinsi">Provinsi</option>
                    		<option value="Nasional">Nasional</option>
                    		<option value="Internasional">Internasional</option>
                    	</select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Kepesertaan*</label>
                    <div class="col-sm-9">
                    	<select id="kepesertaan_update" class="form-control" name="kepesertaan">
                    		<option value="Perorangan">Perorangan</option>
                    		<option value="Beregu">Beregu</option>
                    	</select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Prestasi*</label>
                    <div class="col-sm-9">
                    	<select id="prestasi_update" class="form-control" name="prestasi">
                    		<option value="Juara 1">Juara 1</option>
                    		<option value="Juara 2">Juara 2</option>
                    		<option value="Juara 3">Juara 3</option>
                    		<option value="Harapan 1">Harapan 1</option>
                    		<option value="Harapan 2">Harapan 2</option>
                    	</select>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"><b><i class="fa fa-close"></i></b> Batal</button>
                <button type="submit" class="btn btn-success"><b><i class="fa fa-save"></i></b> Simpan</button>
            </div>
        </form>
    </div>
</div>

@endsection

@section('js')
	@if( Session::has('success') )
		<script type="text/javascript">
			swal("Berhasil", "{{ Session::get('success') }}", "success");
		</script>
	@endif
	@if( $errors->any() )
		<script type="text/javascript">
			swal("Tidak dapat menyimpan data", "{{ Html::ul($errors->all()) }}", "error");
		</script>
	@endif

	<script type="text/javascript">
		$('#modal_update').on('show.bs.modal', function(e){
			$("#form_update").prop('action', $(e.relatedTarget).data('url'));
			$("#bidang_update").val($(e.relatedTarget).data('bidang'));
			$("#nama_update").val($(e.relatedTarget).data('nama'));
			$("#tahun_update").val($(e.relatedTarget).data('tahun'));
			$("#tingkat_update").val($(e.relatedTarget).data('tingkat'));
			$("#kepesertaan_update").val($(e.relatedTarget).data('kepesertaan'));
			$("#prestasi_update").val($(e.relatedTarget).data('prestasi'));
		});		
	</script>
@endsection